apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-incorrect
  namespace: argocd
spec:
  project: blue
  source:
    repoURL: https://github.com/abrumley-mw/argocd-blue.git
    targetRevision: HEAD
    path: app/incorrect
  destination:
    server: https://kubernetes.default.svc
    namespace: blue