apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-two
  namespace: argocd
spec:
  project: blue
  source:
    repoURL: https://github.com/abrumley-mw/argocd-blue.git
    targetRevision: HEAD
    path: app/two
  destination:
    server: https://kubernetes.default.svc
    namespace: blue